global using FirstProject.DataAccess;
global using FirstProject.Interfaces;
global using FirstProject.Models;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Infrastructure;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.EntityFrameworkCore.Migrations;
global using FirstProject.Dtos;
global using AutoMapper;
global using FirstProject.Profiles;
global using FirstProject.Services;
global using FirstProject.Models.Base;
global using AutoInterfaceAttributes;
global using File = FirstProject.Models.Base.File;
global using FirstProject.Controllers;
global using Microsoft.AspNetCore.Http.HttpResults;
global using Microsoft.EntityFrameworkCore.SqlServer.Query.Internal;
global using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
global using Microsoft.Extensions.DependencyInjection;
global using static System.Net.Mime.MediaTypeNames;
