global using ItVacancies.DataAccess;
global using ItVacancies.Interfaces;
global using ItVacancies.Models;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Infrastructure;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.EntityFrameworkCore.Migrations;
global using ItVacancies.Dtos;
global using AutoMapper;
global using ItVacancies.Profiles;
global using ItVacancies.Services;
global using ItVacancies.Models.Base;
global using AutoInterfaceAttributes;
global using File = ItVacancies.Models.Base.File;
global using ItVacancies.Controllers;
global using Microsoft.AspNetCore.Http.HttpResults;
global using Microsoft.EntityFrameworkCore.SqlServer.Query.Internal;
global using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
global using Microsoft.Extensions.DependencyInjection;
global using static System.Net.Mime.MediaTypeNames;
